<?php
/**
 * @file
 * Code for the UA Sites Admin feature.
 */
//Disable seven theme

// theme_disable(array('seven'));
// This should be done in the uams_basic install profile.
//Enable ember theme

function uams_admin_init() {
    $themes = list_themes(); //Get all the available themes
    if($themes['ember']->status == 0) {
        theme_enable(array('ember')); //enable theme
    }

//Disable and uninstall the toolbar module.

 if( module_exists('toolbar')) {
    module_disable(array('toolbar'));
    drupal_uninstall_modules(array('toolbar'));
 } 
}

/**
 * @file
 * Code for the UA Sites Admin feature.
 */

include_once 'uams_admin.features.inc';
