<?php
/**
 * @file
 * Code for the UAQS Navigation feature.
 */

include_once 'uaqs_navigation.features.inc';

/**
 * Implements hook_menu_block_blocks().
 */
function uaqs_navigation_menu_block_blocks() {
  return array(
    // Provides a second-level navigation menu block.
    'uaqs-second-level' => array(
      'menu_name' => MENU_TREE__CURRENT_PAGE_MENU,
      'parent_mlid' => 0,
      'title_link' => FALSE,
      'admin_title' => 'UAQS Second-level Navigation',
      'level' => 2,
      'depth' => 2,
    ),
  );
}

/**
 * Implements hook_theme_registry_alter().
 */
function uaqs_navigation_theme_registry_alter(&$theme_registry) {
  // Find all .tpl.php files in this module's folder recursively.
  $module_path = drupal_get_path('module', 'uaqs_navigation');
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);

  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
