<?php
/**
 * @file
 * Code for the UAQS Fields feature.
 */
include_once 'uaqs_fields.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function uaqs_fields_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['uaqs_teaser_list'] = array(
    'label' => t('UA Bootstrap Media List'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['uaqs_sidebar_teaser_list'] = array(
    'label' => t('UA Bootstrap Minimal Media List'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['uaqs_card'] = array(
    'label' => t('UA Bootstrap Card'),
    'custom settings' => FALSE,
  );
  $entity_info['bean']['view modes']['uaqs_card_overlay'] = array(
    'label' => t('UA Bootstrap Card Overlay'),
    'custom settings' => FALSE,
  );
}