<?php
/**
 * @file
 * Code for the UA Sites Media feature.
 */

include_once 'uams_media.features.inc';

function ua_zen_preprocess_file_entity(&$variables) {
  if ($variables['type'] == 'image') {

    // Alt Text
    if (!empty($variables['field_uams_file_alt_text'])) {
      $variables['content']['file']['#item']['alt'] = $variables['field_uams_file_alt_text']['und'][0]['safe_value'];
    }

    // Title
    if (!empty($variables['field_uams_file_title_text'])) {
      $variables['content']['file']['#item']['title'] = $variables['field_uams_file_title_text']['und'][0]['safe_value'];
    }
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function uams_media_theme_registry_alter(&$theme_registry) {
  // Find all .tpl.php files in this module's folder recursively.
  $module_path = drupal_get_path('module', 'uams_media');
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);

  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

function ua_zen_preprocess_media_oembed(&$variables) {
    $variables['classes_array'][] = 'embed-responsive-item';
}

/**
 * Implements hook_entity_info_alter().
 */
function uams_media_entity_info_alter(&$entity_info) {
  $entity_info['file']['view modes']['full_width'] = array(
    'label' => t('Full width'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['align_left'] = array(
    'label' => t('Align left'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['align_right'] = array(
    'label' => t('Align right'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['square'] = array(
    'label' => t('Square'),
    'custom settings' => TRUE,
  );
}

function ua_zen_media_wysiwyg_token_to_markup_alter(&$element, $tag_info, $settings){
$classes = $element['content']['#attributes']['class'];
$element['content']['#attributes']['class'] = array_diff($classes, array('media'));
}
